### ISSUE TITLE
Add custom props via rest parameter

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-badge#8]
The badge should be updated to support custom props in a similar manner as the slide panel.

See this PR for an example.
https://github.com/cerner/terra-slide-panel/pull/5/files

**Comment by sid141288** [comment]
@mjhenkes we implemented support for custom props as part of the PR https://github.com/cerner/terra-badge/pull/5 .
Can we close this issue ?

**Comment by bjankord** [comment]
Yeah, this issue can be closed.
